# Generated by Django 5.2.8 on 2025-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
